### PR TITLE
Fix file permissions for LICENSE and README.md

### PR DESCRIPTION
**Pull request by peter279k**
Changes proposed in this pull request:
- Let `LICENSE`, `README.md` and `box.json` files be correct file permissions.

@Narno please review :eyes:

### CODE REVIEW

**Comment by Narno** [comment]
Hello @peter279k, what is the goal of this permission changes? Thx.

**Comment by peter279k** [comment]
The goal is about these files should set the non-executable permissions because they're no-executable files.

**Comment by Narno** [comment]
Ah! of course, thank you.

**Comment by ArnaudLigny** [comment]
@all-contributors please add @peter279k for security and code.

**Pull request merged**
